spring:
    server:
        port: 8080
    application:
        name:
    main:
        banner-mode:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
          enabled: true
          path: /h2
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: password
